import { test, expect } from '@playwright/test';
import { CASES } from '../data/cases';
test('complete chapter, reactive labs, keyboard movement, rewards and legacy saves', async ({page}) => {
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/'); await expect(page.getByRole('heading',{name:'Every small kindness begins a great journey.'})).toBeVisible();
 await page.getByRole('link',{name:'Begin the adventure'}).click();
 await expect(page.getByRole('heading',{name:'The Dry Gardener',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Enter the woodland infirmary'}).click();
 const canvas=page.locator('canvas');await canvas.focus();const before=await canvas.getAttribute('data-position');await page.keyboard.down('ArrowLeft');await page.waitForTimeout(250);await page.keyboard.up('ArrowLeft');expect(await canvas.getAttribute('data-position')).not.toBe(before);
 await page.getByRole('button',{name:'Patient · history'}).click();await page.getByRole('button',{name:/Ask about fluid intake/}).click();await expect(page.getByRole('dialog')).toContainText('Vomiting');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Mentor · guidance'}).click();await page.getByRole('button',{name:'Ask mentor (◆2)'}).click();await expect(page.getByText('Mentor’s note')).toBeVisible();
 await page.getByRole('button',{name:'Investigations · lab'}).click();for(const id of CASES[0].expertWorkup){const t=CASES[0].testOptions.find(t=>t.id===id)!;await page.getByRole('button',{name:t.name,exact:false}).click();await expect(page.getByRole('dialog').getByText('✓ '+t.name+' — results:',{exact:true})).toBeVisible();}
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Journal · diagnose'}).click();await page.getByRole('button',{name:CASES[0].correctDiagnosis,exact:true}).click();await page.getByRole('button',{name:'Submit',exact:true}).click();await page.getByRole('button',{name:CASES[0].stagingQuestion!.correct,exact:true}).click();await page.getByRole('button',{name:'Submit',exact:true}).click();for(const m of CASES[0].managementOptions.filter(m=>m.correct))await page.getByRole('button',{name:'☐ '+m.step,exact:true}).click();await page.getByRole('button',{name:'Finish & see score'}).click();await expect(page.getByRole('heading',{name:'Chapter complete'})).toBeVisible();await expect(page.getByText('Grade A',{exact:true})).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nq_scores')!)['aki-prerenal-001'])).toBe(100);await page.goto('/');await expect(page.getByText('200',{exact:true})).toBeVisible();expect(errors).toEqual([]);
});
test('mobile shell, theme/sound persistence, all five case routes and reduced motion',async({page})=>{await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await page.getByRole('button',{name:'Dark mode'}).click();await page.getByRole('button',{name:'Sound off'}).click();await page.reload();await expect(page.getByRole('button',{name:'Light mode'})).toBeVisible();await expect(page.getByRole('button',{name:'Sound on'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/home-mobile.png',fullPage:true});for(const c of CASES){await page.goto('/play/'+c.id);await expect(page.getByRole('heading',{name:c.title,exact:true})).toBeVisible();}await page.goto('/play/aki-prerenal-001');await page.getByRole('button',{name:'Enter the woodland infirmary'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Patient · history'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.screenshot({path:'artifacts/ward-mobile.png',fullPage:true});});
