import test from 'node:test';
import assert from 'node:assert/strict';
import { CASES } from '../data/cases';
import {newProgress,orderTest,askHistory,checkHarmStates,scoreCase} from '../lib/engine';
import {canMove,PLAYER_START,zoneAt} from '../lib/ward';
import {readJourney,saveCase,summary} from '../lib/journey';
for(const c of CASES)test(`${c.id}: original expert workup scoring and idempotent costs`,()=>{let p=newProgress(c.id);for(const h of c.historyOptions.filter(h=>h.key)){p=askHistory(p,h);assert.deepEqual(askHistory(p,h),p);}for(const id of c.expertWorkup){const t=c.testOptions.find(t=>t.id===id)!;p=orderTest(p,t);assert.deepEqual(orderTest(p,t),p);}const r=scoreCase(p,c,c.correctDiagnosis,c.stagingQuestion?.correct??'',c.managementOptions.filter(m=>m.correct).map(m=>m.id));assert.equal(r.total,100);assert.deepEqual([r.diagnosticAccuracy,r.testEfficiency,r.timeEfficiency,r.staging,r.management],[40,25,15,10,10]);assert.equal(scoreCase(p,c,'wrong','wrong',[]).diagnosticAccuracy,0);assert.deepEqual(orderTest({...p,budgetUsed:12},c.testOptions[0]),{...p,budgetUsed:12});});
test('scripted harm is charged once and boundaries/furniture block movement',()=>{const p={...newProgress(CASES[0].id),clock:240};const a=checkHarmStates(p,CASES[0].harmStates);assert.equal(a.progress.penalties.length,1);assert.equal(checkHarmStates(a.progress,CASES[0].harmStates).progress.penalties.length,1);assert.deepEqual(canMove({x:30,y:30},-20,0),{x:30,y:30});assert.deepEqual(canMove({x:380,y:270},20,0),{x:380,y:270});assert.notDeepEqual(canMove(PLAYER_START,3,0),PLAYER_START);assert.equal(zoneAt({x:420,y:590})?.id,'exit');});
test('malformed and legacy storage preserves unknown keys and bounded best scores',()=>{let raw='broken';const store={getItem:()=>raw,setItem:(_:string,v:string)=>{raw=v;}};assert.equal(summary(readJourney(store)).xp,0);saveCase(store,CASES[0].id,80,'');saveCase(store,CASES[0].id,20,'');assert.equal(readJourney(store).scores[CASES[0].id],80);raw=JSON.stringify({other:42,[CASES[0].id]:-3});saveCase(store,CASES[0].id,500,'');assert.equal(JSON.parse(raw).other,42);assert.equal(readJourney(store).scores[CASES[0].id],100);});
